### ISSUE TITLE
setting a Recurring  meeting, then open meeting calendar, occured an error

### ISSUE THREAD

**Issue by archonwang** [MicroHealthLLC/redmine_meeting#1]
setting a Recurring  meeting , then open meeting calendar, occured an error

error log

> Started GET "/projects/demo/meetings/calendar" for 192.168.60.239 at 2016-05-06 08:58:58 +0800
> Processing by MeetingsController#calendar as HTML
>   Parameters: {"project_id"=>"demo"}
>   Current user: admin (id=1)
>   Rendered plugins/redmine_meeting/app/views/meetings/_calendar.html.erb (11.1ms)
>   Rendered plugins/redmine_meeting/app/views/meetings/calendar.html.erb within layouts/base (15.5ms)
> Completed 500 Internal Server Error in 68ms (ActiveRecord: 9.4ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.8ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.4ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (12.8ms)
> 
> ActionView::Template::Error (no implicit conversion of nil into String):
>     11:         <td class="<%= day.month==calendar.month ? 'even' : 'odd' %><%= ' today' if Date.today == day %>">
>     12:           <p class="day-num"><%= day.day %></p>
>     13:           <% @events.select{|meeting|
>     14:             meeting.can_show?(day)
>     15:           }.each do |i| %>
>     16:               <div class="issue" >
>     17:                 <%= image_tag('group.png') %>
>   plugins/redmine_meeting/app/models/meeting.rb:65:in `eval'
>   plugins/redmine_meeting/app/models/meeting.rb:65:in`can_show?'
>   plugins/redmine_meeting/app/views/meetings/_calendar.html.erb:14:in `block in _934984365e7a84f25357f892182c5fd2'
>   plugins/redmine_meeting/app/views/meetings/_calendar.html.erb:13:in`select'
>   plugins/redmine_meeting/app/views/meetings/_calendar.html.erb:13:in `_934984365e7a84f25357f892182c5fd2'
>   plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in`render_with_workflow_enhancements'
>   plugins/redmine_meeting/app/views/meetings/calendar.html.erb:24:in `_e5a65ef6816d5c6de13c632216a0b833'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by b-solution** [comment]
Thanks for updating your branch,
i've updated the issue
