### ISSUE TITLE
add view option to view the day or week's agenda

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/redmine_meeting#10]
create a view next to calendar that says day and show just the appointments for the day

![calendarview1](https://cloud.githubusercontent.com/assets/3675043/15088625/437d21b8-13c4-11e6-97c4-ed0d6d55fd59.png)

create a view next to day that says week and show appointment for the week

![image05](https://cloud.githubusercontent.com/assets/3675043/15088628/51feb12a-13c4-11e6-8ed1-1a730b4be369.png)

**Comment by b-solution** [comment]
done, just click on spcific day to get that record
