### ISSUE TITLE
open calendar occurs 500 error

### ISSUE THREAD

**Issue by archonwang** [MicroHealthLLC/redmine_meeting#11]
when I open redmine meeting, occurs an error

> Started GET "/projects/demo/meetings/calendar" for 192.168.60.239 at 2016-05-07 10:27:28 +0800
> Processing by MeetingsController#calendar as HTML
>   Parameters: {"project_id"=>"demo"}
>   Current user: hui.wang (id=8)
> Completed 500 Internal Server Error in 283ms (ActiveRecord: 33.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.5ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.8ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (2.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.9ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.4ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (128.2ms)
> 
> ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'meeting_users.user_id' in 'where clause': SELECT `meetings`.\* FROM `meetings` WHERE (meeting_users.user_id= 8 OR meetings.user_id = 8) AND ((meetings.subject IS NOT NULL))):
>   plugins/redmine_meeting/app/controllers/meetings_controller.rb:143:in `calendar'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by b-solution** [comment]
Did you do rake redmine:plugins:migrate ?
You have to find a coluln user_id in meeting users columns

**Comment by archonwang** [comment]
I reinstalled the plugin and it's OK, Thanks.

**Comment by bluenevus** [comment]
this plugin is  so awesome and useful.  thanks bilel
