### ISSUE TITLE
Open Redemine meeting occur 500 error

### ISSUE THREAD

**Issue by archonwang** [MicroHealthLLC/redmine_meeting#14]
Open Redemine meeting occur 500 error
the error log is as follows for mysql 

> Started GET "/projects/mac/meetings/calendar" for 192.168.60.239 at 2016-05-09 09:00:51 +0800
> Processing by MeetingsController#calendar as HTML
>   Parameters: {"project_id"=>"mac"}
>   Current user: hui.wang (id=8)
> Completed 500 Internal Server Error in 189ms (ActiveRecord: 35.8ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.7ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.8ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.5ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (14.9ms)
> 
> ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'meeting_users.user_id' in 'where clause': SELECT `meetings`.\* FROM `meetings` WHERE (meeting_users.user_id= 8 OR meetings.user_id = 8) AND ((meetings.subject IS NOT NULL))):
>   plugins/redmine_meeting/app/controllers/meetings_controller.rb:144:in `calendar'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by archonwang** [comment]
it seems that when I used admin it's OK, but when I used someone else, it occured error....

**Comment by b-solution** [comment]
THanks, i've fixed this

**Comment by archonwang** [comment]
tested it OK, Thanks.
