### ISSUE TITLE
it has weekly but you cannot recur every other week or every 3rd week or monthly

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/redmine_meeting#5]
it has weekly but you cannot recur every other week or every 3rd week or monthly.  See example of how to handle recurrence patterns

![pasted file at may 6 2016 8-10 am](https://cloud.githubusercontent.com/assets/3675043/15072863/f65a4df8-1363-11e6-827d-a7e39b31b3f5.png)

**Comment by b-solution** [comment]
done
