### ISSUE TITLE
The main view is the list of meetings.  it should be the calendar

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/redmine_meeting#7]
most people look at a calendar for meetings.  the default view should be the calendar.  there should be a link to view list and add new meeting from the upper right side.  Viewing the list will take you to the standard list that was previously visible.  clicking the new meeting will take you to the add new meeting dialog so they can add a new meeting.

**Comment by b-solution** [comment]
done

**Comment by bluenevus** [comment]
its awesome
