### ISSUE TITLE
remove location check box

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/redmine_meeting#8]
please remove the location check box and lets not make the text field mandatory.  if its blank...no location if they enter field...its a location.  this simplifies entering location

**Comment by b-solution** [comment]
done

**Comment by bluenevus** [comment]
The checkbox was removed however its missing the label that says "Location:"

**Comment by b-solution** [comment]
update the repo
We have only the issue 5 left :)

**Comment by bluenevus** [comment]
looks good
